<?php

/**
 * @file
 * Contains dmc_mbo_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dmc_mbo_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dmc_mbo_migrate module.
    case 'help.page.dmc_mbo_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DMC-MBO custom migrate module.') . '</p>';
      return $output;

    default:
  }
}
